@postId = d37cdd99-50ea-4359-8aaf-cf9a43a74bc8
#Get All Posts
GET https://localhost:7277/api/v1/posts

###

#Get By Id
GET https://localhost:7277/api/v1/posts/{{postId}}

###

#Create Post
POST https://localhost:7277/api/v1/posts
Content-Type: application/json

{
    "name":"Post Item 4"
}

###

PUT https://localhost:7277/api/v1/posts/71cb83f5-d893-4655-8c83-1e38a9573fb3
Content-Type: application/json

{
  "name":"Post Item 3"
}